# Generated by Django 5.2.5 on 2025-08-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('account_no', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.customer')),
                ('company_type', models.TextField(choices=[('P', 'Private'), ('U', 'Public'), ('G', 'Government')], default='P')),
            ],
            bases=('customer.customer',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.customer')),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M')),
                ('date_of_birth', models.DateField()),
            ],
            bases=('customer.customer',),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.AutoField(primary_key=True, serialize=False)),
                ('door_no', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customer.customer')),
            ],
        ),
    ]
