---
- name: Install java on target machines
  hosts: all
  become: yes
  vars:
   java_version: "21"

  tasks:
   - name: update apt cache (Debian/Ubuntu)
     apt:
      update_cache: yes
     when: ansible_os_family == "Debian"
   - name: Install Java on Debian or Ubuntu
     apt:
      name: "openjdk-{{ java_version }}-jdk"
      state: present
     when: ansible_os_family == "Debian"
